# .github/workflows/meterian.yml

name: Meterian Scanner workflow

on: push

jobs:
    meterian_scan:
        name: Meterian client scan
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout
            uses: actions/checkout@v2
          - name: Meterian Scanner
            uses: MeterianHQ/meterian-github-action@v1.0.10
            env:
              METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}
